### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by mksanderson** [grantHarris/leaflet-popup-angular#2]
Hi,

This is a great extension of the Leaflet popup class and has saved me a lot of trouble. Would love to see it ready for Bower, and with a little more documentation.

Would be great if the template could directly reference data available in the controller it is being created within instead of having the isolated scope it seems to have (requiring a controller or passing in data via setContent).

Thanks,

Matt

**Comment by grantHarris** [comment]
Hi Matt,

Sounds good. I'm going to be doing a new release within the next week and I'll add a bower.json.

I'll take a look at the scope issue. Perhaps have an options param where you can pass in a particular 'this'.

**Comment by grantHarris** [comment]
I've pushed the package to bower
