### ISSUE TITLE
$injector undefined

### ISSUE THREAD

**Issue by guytomoki** [grantHarris/leaflet-popup-angular#3]
Getting
`Uncaught TypeError: Cannot read property 'get' of undefined`
on 
`var $rootScope = $injector.get('$rootScope'),`
`$compile = $injector.get('$compile'),`
`$controller = $injector.get('$controller');`
when `ng-app` is set on a child of `<html>` (such as `<body>`).

`angular.element('[ng-app]').injector()` should fix the issue.

**Comment by grantHarris** [comment]
Thanks, I'll take a look at it this week.

**Comment by grantHarris** [comment]
Looking up query selectors is not supported by jqLite that ships with angular. It seems a little heavy to require jQuery as a dependancy for such a case.

I would welcome a PR if you have a nice solution that doesn't require jQuery.

**Comment by grantHarris** [comment]
See the latest release 1.0.1.
